# -*- coding: utf-8 -*-
"""DSProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKO5Qwhs25M7TqilB1bc7q_D9WEOEjp7
"""

import pandas as pd
import numpy as np

"""**Loading the data**"""

df= pd.read_csv("/content/drive/MyDrive/DS_PROJECT/car_sales_data.csv")
df.head()

"""**Data cleaning and processing**"""

#checking for null values
df.isna().any()

#studying the data
df.describe()

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df2= df
df2['Manufacturer']= le.fit_transform(df2['Manufacturer'])
print(dict(zip(le.classes_, range(len(le.classes_)))))
df2['Model']= le.fit_transform(df2['Model'])
print(dict(zip(le.classes_, range(len(le.classes_)))))
df2

df2['Fuel type']= le.fit_transform(df2['Fuel type'])
print(dict(zip(le.classes_, range(len(le.classes_)))))
df2

"""**Prices are in GBP (Great Britain Pound)**"""

X= df2.drop('Price', axis=1)
y= df2['Price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.2, random_state=42)

"""**Model building**"""

from sklearn.ensemble import RandomForestRegressor
model= RandomForestRegressor()
model.fit(X_train, y_train)

yp=model.predict(X_test)

model.score(X_test, y_test)

from sklearn.metrics import r2_score
print(r2_score(y_test, yp))

import pickle

with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

from google.colab import files
files.download("model.pkl")